<?php

namespace App\Helpers;

class Ratios
{
    const CATALOGO = [
        'LIQUIDEZ_CORRIENTE'=>1,
        'LIQUIDEZ_ACIDA'=>2,
        'ACTIVO_NETO'=>3,
        'EFECTIVO'=>4,
        'ROTACION_INVENTARIOS'=>5,
        'DIAS_INVENTARIOS'=>6,
        'ROTACION_CUENTAS_COBRO'=>7,
        'MEDIO_COBRANZA'=>8,
        'ROTACION_CUENTAS_POR_PAGAR'=>9,
        'PERIODO_MEDIO_PAGO'=>10,
        'ROTACION_ACTIVO_TOTAL'=>11,
        'ROTACION_ACTIVO_FIJOS'=>12,
        'MARGEN_BRUTO'=>13,
        'MARGEN_OPERATIVO'=>14,
        'GRADO_ENDEUDAMIENTO'=>15,
        'GRADO_PROPIEDAD'=>16,
        'ENDUDAMIENTO_PATRIOMONIO'=>17,
        'COBERTURA_GASTOS'=>18,
        'RENTABILIDAD_NETA'=>19,
        "RENTABILIDAD_ACTIVO"=>20,
        "RENTABILIDAD_VENTAS"=>21,
        "RENTABILIDAD_INVERSION" => 22
    ];
}
